global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:9101']
    scrape_interval: 5s
    metrics_path: '/metrics'
  
  - job_name: 'service-desk'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Service Desk'
  
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] #env later
        labels:
          application: 'User Service'